# Generated by Django 5.2.17 on 2026-10-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HCSTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=32, unique=True)),
                ('topic_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HCSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('evidence_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('milestone_id', models.CharField(blank=True, max_length=32)),
                ('proof_hash', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='QUEUED', max_length=12)),
                ('sequence_number', models.BigIntegerField(blank=True, null=True)),
                ('consensus_timestamp', models.CharField(blank=True, max_length=32)),
                ('transaction_id', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('readback_ok', models.BooleanField(null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hcs.hcstopic')),
            ],
            options={
                'ordering': ['sequence_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('topic', 'event_type', 'proof_hash'), name='uniq_hcs_hash')],
            },
        ),
    ]
