# Generated by Django 5.2.17 on 2026-10-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmittedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(max_length=40)),
                ('project_id', models.CharField(db_index=True, max_length=32)),
                ('envelope', models.JSONField()),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True)),
                ('project_id', models.CharField(db_index=True, max_length=32)),
                ('milestone_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('milestone_source', models.CharField(blank=True, default='', max_length=16)),
                ('source', models.CharField(choices=[('COMMIT', 'Commit'), ('PULL_REQUEST', 'Pull Request'), ('REVIEW', 'Review'), ('MANUAL', 'Manual')], max_length=16)),
                ('source_ref', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content_digest', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('ANCHORED', 'Anchored')], db_index=True, default='COLLECTED', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('project_id', 'source', 'source_ref'), name='uniq_evidence_source_ref')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_hash', models.CharField(db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('verdict', models.CharField(max_length=16)),
                ('method', models.CharField(max_length=16)),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='evidence.evidence')),
            ],
        ),
    ]
