# Generated by Django 5.2.17 on 2026-10-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokenization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('total_supply', models.PositiveIntegerField()),
                ('decimals', models.PositiveSmallIntegerField(default=0)),
                ('token_id', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=150)),
                ('hashscan_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Created'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tokenization', to='project_catalog.project')),
            ],
        ),
        migrations.CreateModel(
            name='WalletConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='HashPack', max_length=50)),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected')], default='DISCONNECTED', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_connection', to='project_catalog.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('units', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ALLOCATED', 'Allocated'), ('RELEASED', 'Released')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_units', to='project_catalog.milestone')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HederaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('WORKER', 'Worker'), ('TREASURY', 'Treasury')], max_length=20)),
                ('token_associated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hedera_accounts', to='project_catalog.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'account_id'), name='unique_hedera_account_per_project')],
            },
        ),
    ]
