# Generated by Django 5.2.17 on 2026-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0002_tokenization_walletconnection_workunit_hederaaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(max_length=4),
        ),
    ]
