# Generated by Django 5.2.8 on 2026-10-01 18:11

import command_center.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('BLOCKED', 'Blocked'), ('OFFLINE', 'Offline')], default='IDLE', max_length=16)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='AgentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(max_length=180)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('task_type', models.CharField(max_length=80)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='command_center.agent')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('metric_key', models.CharField(max_length=80)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('source', models.CharField(default='mock', max_length=32)),
                ('measured_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ('-measured_at',),
                'indexes': [models.Index(fields=['project_id', 'metric_key', 'measured_at'], name='metric_project_key_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='IN_APP', max_length=24)),
                ('recipient', models.CharField(blank=True, max_length=128)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='command_center.agentalert')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('milestone_id', models.CharField(blank=True, max_length=128, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('trace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('FAILED', 'Failed')], default='RECEIVED', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['project_id', 'received_at'], name='evt_project_received_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('span_id', models.CharField(default=command_center.models.new_span_id, max_length=32)),
                ('parent_span_id', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='command_center.agent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='command_center.systemevent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block'), ('HUMAN_REVIEW', 'Human review'), ('PENDING', 'Pending')], max_length=16)),
                ('reason_code', models.CharField(max_length=80)),
                ('reason', models.CharField(max_length=500)),
                ('policy_version', models.CharField(blank=True, max_length=40)),
                ('decided_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='command_center.agent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='command_center.systemevent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('span_id', models.CharField(max_length=32)),
                ('action_type', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=24)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='command_center.agent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='command_center.systemevent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
