# Generated by Django 5.2.8 on 2026-10-01 18:14

import command_center.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('span_id', models.CharField(default=command_center.models.new_span_id, max_length=32)),
                ('parent_span_id', models.CharField(blank=True, max_length=32, null=True)),
                ('actor_type', models.CharField(default='SYSTEM', max_length=24)),
                ('actor_id', models.CharField(blank=True, max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=24)),
                ('decision', models.CharField(blank=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='command_center.systemevent')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['project_id', 'created_at'], name='audit_project_time_idx')],
            },
        ),
    ]
