# Generated by Django 5.2.8 on 2026-10-03 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_center', '0004_local_project_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementMonitorAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('OBSERVED', 'Observation received'), ('UNAVAILABLE', 'Source unavailable'), ('INVALID', 'Invalid observation'), ('ERROR', 'Source error')], max_length=16)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('observed_status', models.CharField(blank=True, max_length=24)),
                ('transaction_id', models.CharField(blank=True, max_length=128)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-checked_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.CharField(max_length=128, unique=True)),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('POLICY_PENDING', 'Policy pending'), ('AUTHORIZED', 'Authorized'), ('POLICY_BLOCKED', 'Blocked by policy'), ('SUBMITTED_BY_OWNER', 'Submitted by owner'), ('OBSERVED_PENDING', 'Observed pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], default='REQUESTED', max_length=24)),
                ('transaction_id', models.CharField(blank=True, max_length=128)),
                ('network', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('last_observed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', 'settlement_id'),
            },
        ),
        migrations.CreateModel(
            name='SettlementTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('transaction_id', models.CharField(blank=True, max_length=128)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('observed_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='agent_version',
            field=models.CharField(default='dev4-agent/1.0', max_length=40),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='input_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='reason_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='source_refs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='agentexecution',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('RETRYABLE_FAILURE', 'Retryable failure'), ('PERMANENT_FAILURE', 'Permanent failure')], default='QUEUED', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='agentexecution',
            constraint=models.UniqueConstraint(fields=('agent', 'event'), name='uniq_agent_event_execution'),
        ),
        migrations.AddField(
            model_name='settlementmonitorattempt',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitor_attempts', to='command_center.settlementrecord'),
        ),
        migrations.AddField(
            model_name='settlementtransition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_transitions', to='command_center.systemevent'),
        ),
        migrations.AddField(
            model_name='settlementtransition',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='command_center.settlementrecord'),
        ),
        migrations.AddConstraint(
            model_name='settlementtransition',
            constraint=models.UniqueConstraint(fields=('settlement', 'event'), name='uniq_settlement_event_transition'),
        ),
    ]
