# Generated by Django 5.2.8 on 2026-10-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_center', '0005_phase5_agents_and_settlement_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_version',
            field=models.CharField(default='dev4-agent/1.0', max_length=40),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
