# Generated by Django 5.2.8 on 2026-10-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_center', '0006_phase5_agent_health_and_monitor_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementrecord',
            name='consensus_timestamp',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='settlementtransition',
            name='consensus_timestamp',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
