# Generated by Django 5.2.8 on 2026-10-04 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_center', '0007_phase5_settlement_finality_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreference',
            name='is_demo_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev4_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('FREELANCER', 'Freelancer'), ('CLIENT', 'Client'), ('ADMIN', 'Admin')], default='FREELANCER', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
                ('github_login', models.CharField(blank=True, max_length=39)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('is_demo_only', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'id'),
            },
        ),
    ]
