# Generated by Django 5.2.8 on 2026-10-04 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_center', '0008_freelancer_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreference',
            name='provenance',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTED', 'Imported'), ('GITHUB_API', 'GitHub API'), ('HEDERA_MIRROR_NODE', 'Hedera Mirror Node'), ('TEST_ONLY', 'Test only')], max_length=24),
        ),
        migrations.CreateModel(
            name='ProjectAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('total_work_units', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_deadline', models.DateField(blank=True, null=True)),
                ('github_repository', models.CharField(blank=True, max_length=200)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('provenance', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTED', 'Imported'), ('GITHUB_API', 'GitHub API'), ('HEDERA_MIRROR_NODE', 'Hedera Mirror Node'), ('TEST_ONLY', 'Test only')], default='MANUAL', max_length=24)),
                ('plan_status', models.CharField(default='UNKNOWN', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='command_center.projectreference')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('planned_work_units', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_work_units', models.PositiveIntegerField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('UNKNOWN', 'Unknown')], default='PROPOSED', max_length=16)),
                ('provenance', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTED', 'Imported'), ('GITHUB_API', 'GitHub API'), ('HEDERA_MIRROR_NODE', 'Hedera Mirror Node'), ('TEST_ONLY', 'Test only')], default='MANUAL', max_length=24)),
                ('source_event_id', models.CharField(blank=True, max_length=128)),
                ('is_demo_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='command_center.projectreference')),
            ],
            options={
                'ordering': ('order', 'milestone_id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('AGREEMENT', 'Agreement'), ('MILESTONE', 'Milestone'), ('RELEASE', 'Release')], max_length=12)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('provenance', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTED', 'Imported'), ('GITHUB_API', 'GitHub API'), ('HEDERA_MIRROR_NODE', 'Hedera Mirror Node'), ('TEST_ONLY', 'Test only')], default='MANUAL', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev4_project_approvals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='command_center.projectreference')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='command_center.projectmilestone')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=128)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('GITHUB_API', 'GitHub API'), ('TEST_ONLY', 'Test only')], max_length=24)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNKNOWN', 'Unknown'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=12)),
                ('repository', models.CharField(blank=True, max_length=200)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('proof_hash', models.CharField(blank=True, max_length=64)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('source_event_id', models.CharField(blank=True, max_length=128)),
                ('is_demo_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_submissions', to='command_center.projectreference')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev4_evidence_submissions', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_submissions', to='command_center.projectmilestone')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FREELANCER', 'Freelancer'), ('CLIENT', 'Client')], default='FREELANCER', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev4_members_added', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='command_center.projectreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev4_project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='uniq_dev4_project_member')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.UniqueConstraint(fields=('project', 'milestone_id'), name='uniq_dev4_project_milestone'),
        ),
        migrations.AddConstraint(
            model_name='evidencesubmission',
            constraint=models.UniqueConstraint(fields=('project', 'evidence_id'), name='uniq_dev4_project_evidence'),
        ),
    ]
