# Generated by Django 5.2.17 on 2026-10-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=32)),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('worker_github', models.CharField(blank=True, max_length=100)),
                ('webhook_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=40)),
                ('repository', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField()),
                ('outcome', models.CharField(blank=True, max_length=60)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True)),
                ('author', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('committed_at', models.DateTimeField()),
                ('files_changed', models.IntegerField(default=0)),
                ('milestone_id', models.CharField(blank=True, max_length=32, null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='githubint.githubrepository')),
            ],
            options={
                'ordering': ['-committed_at'],
                'constraints': [models.UniqueConstraint(fields=('repo', 'sha'), name='uniq_commit')],
            },
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.BigIntegerField()),
                ('pr_number', models.IntegerField()),
                ('reviewer', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('submitted_at', models.DateTimeField()),
                ('milestone_id', models.CharField(blank=True, max_length=32, null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='githubint.githubrepository')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('repo', 'review_id'), name='uniq_review')],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('merged', models.BooleanField(default=False)),
                ('additions', models.IntegerField(blank=True, null=True)),
                ('deletions', models.IntegerField(blank=True, null=True)),
                ('labels', models.JSONField(default=list)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('milestone_id', models.CharField(blank=True, max_length=32, null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulls', to='githubint.githubrepository')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('repo', 'number'), name='uniq_pr')],
            },
        ),
    ]
